theme: just-the-docs
remote_theme: just-the-docs/just-the-docs
title: Modelling from measurements - Documentation
description: Documentation for the codes asked during the PhD course 'Modelling from Measurements' at Politecnico di Milano.
